{% set name = "dtreeviz" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dtreeviz-{{ version }}.tar.gz
  sha256: 0d87b00e78c95b45f24fb6f3a9efbbb34169a8d51aa7b5c7194bf4431443d4c8

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv


outputs:
  - name: {{ name }}
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - colour
        - python-graphviz >=0.9
        - matplotlib-base
        - numpy
        - pandas
        - pillow
        - pytest
        - scikit-learn

    test:
      imports:
        - dtreeviz
      commands:
        - pip check
      requires:
        - pip
  - name: {{ name }}-extended
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - {{ pin_subpackage(name, exact=True) }}
        - pyspark
        - py-xgboost
        - lightgbm

    test:
      imports:
        - dtreeviz
        - dtreeviz.models
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/parrt/dtreeviz
  summary: A python library for decision tree visualization and model interpretation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - pplonski
